<%@ Page Title="" Language="C#" MasterPageFile="~/main.master" AutoEventWireup="true" CodeFile="ChinhSachBaoHanh.aspx.cs" Inherits="ChinhSachBaoHanh" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; text-align: center;">
    <span style="box-sizing: border-box; font-size: 20pt; color: rgb(255, 0, 0);">QUI ĐỊNH VÀ CHÍNH SÁCH BẢO HÀNH SẢN PHẨM </span>
</p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    <span style="box-sizing: border-box; font-size: 20pt;"><strong style="box-sizing: border-box; font-weight: bold;">I. QUI ĐỊNH BẢO HÀNH SẢN PHẨM </strong></span>
</p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    <span style="box-sizing: border-box; font-size: 15pt;">Sản phẩm phát sinh bảo hành được HNC-SMARTPHONE tiếp nhận và kiểm tra lỗi sản phẩm tại chỗ có sự giám sát của khách hàng và nhân viên tiếp nhận.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    <span style="box-sizing: border-box; font-size: 15pt;"><strong style="box-sizing: border-box; font-weight: bold;">Sản phẩm lỗi do nhà sản xuất:</strong></span></p>
<ul style="box-sizing: border-box; list-style: outside; margin: 0px 0px 10px; padding: 0px 0px 0px 15px; color: rgb(51, 51, 51); font-family: &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    <li style="box-sizing: border-box;"><span style="box-sizing: border-box; font-size: 15pt;">Phát hiện ra lỗi: sản phẩm được xử lý bảo hành theo chính sách bảo hành của HNC-SMARTPHONE và hãng (tùy trường hợp cụ thể sẽ báo với khách hàng ngay tại thời điểm kiểm tra)</span></li>
    <li style="box-sizing: border-box;"><span style="box-sizing: border-box; font-size: 15pt;">Chưa phát hiện ra lỗi ngay: HNC-SMARTPHONE sẽ giữ lại sản phẩm để gửi về hãng tiếp tục kiểm tra, thời gian kiểm tra tùy vào loại sản phẩm-tối đa 14 ngày làm việc (ngày làm việc không tính T7 &amp; CN).</span></li>
</ul>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    <span style="box-sizing: border-box; font-size: 15pt;"><strong style="box-sizing: border-box; font-weight: bold;">Sản phẩm lỗi do người sử dụng:</strong></span></p>
<ul style="box-sizing: border-box; list-style: outside; margin: 0px 0px 10px; padding: 0px 0px 0px 15px; color: rgb(51, 51, 51); font-family: &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    <li style="box-sizing: border-box;"><span style="box-sizing: border-box; font-size: 15pt;"><em style="box-sizing: border-box;">Trường hợp này sản phẩm nằm ngoài chính sách bảo hành, HNC-SMARTPHONE hỗ trợ chuyển bảo hành về TTBH của hãng xử lý:</em></span><ul style="box-sizing: border-box; list-style: outside circle; margin: 0px; padding: 0px 0px 0px 15px;">
        <li style="box-sizing: border-box;"><span style="box-sizing: border-box; font-size: 15pt;"><em style="box-sizing: border-box;">Có khả năng sửa chữa/thay thế: khách hàng chịu phí sửa chữa nếu có và HNC-SMARTPHONE sẽ thông báo với khách hàng ngay tại thời điểm có thông tin.</em></span></li>
        <li style="box-sizing: border-box;"><span style="box-sizing: border-box; font-size: 15pt;"><em style="box-sizing: border-box;">Không có khả năng sửa chữa được: HNC-SMARTPHONEsẽ hoàn trả lại sản phẩm lỗi cho khách hàng.</em></span></li>
        </ul>
    </li>
</ul>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    <span style="box-sizing: border-box; font-size: 15pt; color: rgb(255, 0, 0);"><em style="box-sizing: border-box;"><strong style="box-sizing: border-box; font-weight: bold;">* Lưu ý:</strong><span>&nbsp;</span>tất cả các sản phẩm nằm ngoài chính sách bảo hành có thời gian xử lý và phản hồi tùy thuộc vào TTBH của hãng, <span style="box-sizing: border-box; font-size: 15pt;">HNC-SMARTPHONE </span>sẽ cập nhật liên tục để khách hàng có thể nắm thông tin tùy trường hợp cụ thể.</em></span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    <span style="box-sizing: border-box; font-size: 20pt;"><strong style="box-sizing: border-box; font-weight: bold;">II. THỜI GIAN BẢO HÀNH &amp; HỖ TRỢ KỸ THUẬT</strong></span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    <span style="box-sizing: border-box; font-size: 15pt;"><strong style="box-sizing: border-box; font-weight: bold;">Trung tâm CSKH và Bảo Hành HNC-SMARTPHONE</strong></span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    <span style="box-sizing: border-box; font-size: 15pt;"><strong style="box-sizing: border-box; font-weight: bold;">Thành phố Hồ Chí Minh:</strong></span></p>
<ul style="box-sizing: border-box; list-style: outside; margin: 0px 0px 10px; padding: 0px 0px 0px 15px; color: rgb(51, 51, 51); font-family: &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    <li style="box-sizing: border-box;"><span style="box-sizing: border-box; font-size: 15pt;"><strong style="box-sizing: border-box; font-weight: bold;">Địa chỉ: 140 Lê Trọng Tấn, Phường Tây Thạnh, quận Tân Phú.</strong></span></li>
    <li style="box-sizing: border-box;"><span style="box-sizing: border-box; font-size: 15pt;"><strong style="box-sizing: border-box; font-weight: bold;">Điện thoại:<span>&nbsp;</span><span style="box-sizing: border-box;">0823239254</span></strong></span></li>
    <li style="box-sizing: border-box;"><span style="box-sizing: border-box; font-size: 15pt;"><strong style="box-sizing: border-box; font-weight: bold;">Thời gian tiếp nhận bảo hành và hỗ trợ kỹ thuật: 8h30 – 21h (Thứ 2 – Chủ Nhật)</strong></span></li>
</ul>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    <span style="box-sizing: border-box; font-size: 15pt;"><strong style="box-sizing: border-box; font-weight: bold;">Hà Nội:</strong></span></p>
<ul style="box-sizing: border-box; list-style: outside; margin: 0px 0px 10px; padding: 0px 0px 0px 15px; color: rgb(51, 51, 51); font-family: &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    <li style="box-sizing: border-box;"><span style="box-sizing: border-box; font-size: 15pt;"><strong style="box-sizing: border-box; font-weight: bold;">Địa chỉ: 37 Ngõ 121 Thái Hà, Phường Trung Liệt, Quận Đống Đa.</strong></span></li>
    <li style="box-sizing: border-box;"><span style="box-sizing: border-box; font-size: 15pt;"><strong style="box-sizing: border-box; font-weight: bold;">Thời gian tiếp nhận bảo hành và hỗ trợ kỹ thuật: 8h30 – 18h (Thứ 2 – Thứ 7), 8h30 – 17h ( Chủ Nhật )</strong></span></li>
    <li style="box-sizing: border-box;"><span style="box-sizing: border-box; font-size: 15pt;">Khách hàng vui lòng liên hệ và mang sản phẩm đã mua tại HNC-SMARTPHONE đến Trung tâm CSKH và Bảo Hành HNC-SMARTPHONE để được hỗ trợ.</span></li>
    <li style="box-sizing: border-box;"><span style="box-sizing: border-box; font-size: 15pt;">Khách hàng vui lòng xuất trình phiếu tiếp nhận lúc nhận trả bảo hành.</span><ul style="box-sizing: border-box; list-style: outside circle; margin: 0px; padding: 0px 0px 0px 15px;">
        <li style="box-sizing: border-box;"><span style="box-sizing: border-box; font-size: 15pt;"><strong style="box-sizing: border-box; font-weight: bold;">Đổi mới ngay lập tức sản phẩm bị lỗi do nhà sản xuất trong 30 ngày đầu tiên.<br /> Điều kiện đổi sản phẩm bị lỗi như sau:</span><ul style="box-sizing: border-box; list-style: outside circle; margin: 0px; padding: 0px 0px 0px 15px;">
            <li style="box-sizing: border-box;"><span style="box-sizing: border-box; font-size: 15pt;">Sản phẩm và hộp sản phẩm phải còn giữ nguyên vẹn bao gồm tất cả phụ kiện đi kèm, sách hướng dẫn.</span></li>
            <li style="box-sizing: border-box;"><span style="box-sizing: border-box; font-size: 15pt;">Có tem xác nhận của HNC-SMARTPHONE bao gồm: tem bảo hành và tem chống giả.</span></li>
            <li style="box-sizing: border-box;"><span style="box-sizing: border-box; font-size: 15pt;">Mã số IMEI, Serial Number S/N phải còn nguyên vẹn.</span></li>
            <li style="box-sizing: border-box;"><span style="box-sizing: border-box; font-size: 15pt;">Sản phẩm không bị tương tác vật lý như: trầy xước, móp méo, biến dạng, tiếp xúc chất lỏng.</span></li>
            </ul>
        </li>
        </ul>
    </li>
</ul>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    <span style="box-sizing: border-box; font-size: 15pt; color: rgb(255, 0, 0);"><em style="box-sizing: border-box;"><strong style="box-sizing: border-box; font-weight: bold;">* Lưu ý:</strong><span>&nbsp;</span>Các sản phẩm không thỏa các điều kiện trên sẽ được <span style="box-sizing: border-box; font-size: 15pt;">HNC-SMARTPHONE</span> xử lý bảo hành theo chính sách của hãng.</em></span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    <span style="box-sizing: border-box; font-size: 15pt; color: rgb(255, 0, 0);"><em style="box-sizing: border-box;"><strong style="box-sizing: border-box; font-weight: bold;">* LƯU Ý:</strong><span>&nbsp;</span>MỘT SỐ TRƯỜNG HỢP ĐẶC BIỆT KHI NHẬN ĐƯỢC THÔNG BÁO TỪ CÁC TTBH CỦA HÃNG VỀ THỜI GIAN KIỂM TRA VÀ XỬ LÝ CÓ THỂ LÂU HƠN DỰ KIẾN BÊN TRÊN, GEARVN SẼ THÔNG BÁO NGAY VỚI KHÁCH HÀNG TẠI THỜI ĐIỂM TIẾP NHẬN THÔNG TIN PHÁT SINH.</em></span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    <span style="box-sizing: border-box; font-size: 20pt;"><strong style="box-sizing: border-box; font-weight: bold;">III.&nbsp;BẢO HÀNH SẢN PHẨM SMARTPHONE:</strong></span></p>
<ul style="box-sizing: border-box; list-style: outside; margin: 0px 0px 10px; padding: 0px 0px 0px 15px; color: rgb(51, 51, 51); font-family: &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    <li style="box-sizing: border-box;"><span style="box-sizing: border-box; font-size: 15pt;">SmartPhone đủ điều kiện bảo hành đảm bảo các tiêu chí:</span><ul style="box-sizing: border-box; list-style: outside circle; margin: 0px; padding: 0px 0px 0px 15px;">
        <li style="box-sizing: border-box;"><span style="box-sizing: border-box; font-size: 15pt;">Sản phẩm phải đủ hai loại tem của HNC-SMARTPHONE bao gồm tem bảo hành và tem chống giả và vẫn còn nằm trong thời gian bảo hành của HNC-SMARTPHONE .</span></li>
        <li style="box-sizing: border-box;"><span style="box-sizing: border-box; font-size: 15pt;">Tem còn nguyên vẹn hoặc bị dán bất kì loại tem nào khác đè lên tem bảo hành của HNC-SMARTPHONE hoặc tem của hãng/ nhà phân phối.</span></li>
        <li style="box-sizing: border-box;"><span style="box-sizing: border-box; font-size: 15pt;">Số serial trên các sản phẩm phải còn nguyên vẹn không được bong tróc hoặc mất số serial.</span></li>
        </ul>
    </li>
</ul>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    <span style="box-sizing: border-box; font-size: 15pt;"><strong style="box-sizing: border-box; font-weight: bold;">Sản phẩm lỗi do nhà sản xuất</strong><em style="box-sizing: border-box;">:</em></span></p>
<ul style="box-sizing: border-box; list-style: outside; margin: 0px 0px 10px; padding: 0px 0px 0px 15px; color: rgb(51, 51, 51); font-family: &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    <li style="box-sizing: border-box;"><span style="box-sizing: border-box; font-size: 15pt;">Phát hiện ra lỗi ngay:</span><ul style="box-sizing: border-box; list-style: outside circle; margin: 0px; padding: 0px 0px 0px 15px;">
        <li style="box-sizing: border-box;"><span style="box-sizing: border-box; font-size: 15pt;">bảo hành 1 đổi mới ngay lập tức trong suốt thời gian bảo hành. Sản phẩm đổi mới sẽ không kèm hộp</span></li>
        <li style="box-sizing: border-box;"><span style="box-sizing: border-box; font-size: 15pt;">bảo hành<span>&nbsp;</span><strong style="box-sizing: border-box; font-weight: bold;">1 đổi 1 tương đương&nbsp;</strong>ngay lập tức&nbsp;trong suốt thời gian bảo hành.</span></li>
        </ul>
    </li>
    <li style="box-sizing: border-box;"><span style="box-sizing: border-box; font-size: 15pt;">Chưa phát hiện ra lỗi ngay:</span><ul style="box-sizing: border-box; list-style: outside circle; margin: 0px; padding: 0px 0px 0px 15px;">
        <li style="box-sizing: border-box;"><span style="box-sizing: border-box; font-size: 15pt;">Sản phẩm sẽ được nhận lại và gửi lên TTBH của hãng để hỗ trợ kiểm tra thêm.</span></li>
        <li style="box-sizing: border-box;"><span style="box-sizing: border-box; font-size: 15pt;">Trong thời gian chờ kiểm tra, HNC-SMARTPHONE sẽ ký gửi sản phẩm khác để khách hàng có thể dùng tạm trong thời gian chờ đợi.</span></li>
        </ul>
    </li>
</ul>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    <span style="box-sizing: border-box; color: rgb(255, 0, 0);"><span style="box-sizing: border-box; font-size: 15pt;"><em style="box-sizing: border-box;"><strong style="box-sizing: border-box; font-weight: bold;">* Lưu ý:</strong>&nbsp;</em>Sản<em style="box-sizing: border-box;"><span>&nbsp;</span>phẩm<span>&nbsp;</span>được phát hiện ngay tại thời điểm kiểm tra<span>&nbsp;</span>mà không có sản phẩm đổi ngay cho khách (một số yếu tố khách quan: sản phẩm đã ngừng sản xuất, hãng và HNC-SMARTPHONE hết hàng dự trữ bảo hành), HNC-SMARTPHONE cũng sẽ ký gửi sản phẩm khác để khách hàng có thể dùng tạm trong thời gian chờ<span>&nbsp;</span>xử lý.</em></span></span></p>
    </strong>
</asp:Content>

